name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#Run npm run linting
jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
        working-directory: ./app

      - name: Run ESLint
        run: npm run lint:fix
        working-directory: ./app

      - name: Run Prettier
        run: npm run prettier
        working-directory: ./app
