name: Run Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

#Run npm run test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: npm install, build, and test
        run: |
          cd app
          npm install
          npm run test --if-present
