name: Typechecking

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#Run npm run linting
jobs:
  lint:
    name: 🔤 Typechecking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: npm install, build and typecheck
        run: |
          cd app
          npm install
          npm run build --if-present
          npm run typechecking --if-present
